apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osticket-mariadb
  namespace: osticket
  labels:
    app: osticket-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osticket-mariadb
  serviceName: osticket-mariadb
  template:
    metadata:
      labels:
        app: osticket-mariadb
    spec:
      containers:
      - name: osticket-mariadb
        image: mariadb:lts@sha256:7d3fd2f513cc2a5edad3a6aed2d7154ab1503ee3c3362bb54d8cb6112959b4f2
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: osticket-secret
              key: mariadb_root_password
        - name: MARIADB_DATABASE
          value: "osticket"
        - name: MARIADB_USER
          value: "osticket"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: osticket-secret
              key: osticket_db_password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: osticket-mariadb-volume
      volumes:
      - name: osticket-mariadb-volume
        persistentVolumeClaim:
          claimName: osticket-data-pvc
