apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phpipam-mysql
  namespace: phpipam
  labels:
    app: phpipam-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpipam-mysql
  serviceName: phpipam-mysql
  template:
    metadata:
      labels:
        app: phpipam-mysql
    spec:
      containers:
      - name: phpipam-mysql
        image: mysql:8.4@sha256:ac80b6e09e5b12b4f9d5cd4f6425e43464247aa4ba4f6169da5daf59e5877f7d
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phpipam-secret
              key: mysql_root_password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: phpipam-mysql-volume
      volumes:
      - name: phpipam-mysql-volume
        persistentVolumeClaim:
          claimName: phpipam-data-pvc
