apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: searxng
  namespace: ai
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  serviceName: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
      - name: searxng
        image: searxng/searxng:latest@sha256:8afd2f3ddc32a001ff965e50b1b50f0c3aa89aa92b9f8746022d9aeb12bbca24
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/searxng
          name: searxng-volume
      volumes:
      - name: searxng-volume
        persistentVolumeClaim:
          claimName: searxng-data-pvc
