apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openssh-server
  namespace: openssh-server
  labels:
    app: openssh-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openssh-server
  serviceName: openssh-server
  template:
    metadata:
      labels:
        app: openssh-server
    spec:
      containers:
      - name: openssh-server
        image: lscr.io/linuxserver/openssh-server:latest@sha256:451b9fa4acee8ec9d7b4620aa91dc8e6a827923fc7b7be16517f35994b2b69c6
        imagePullPolicy: Always
        ports:
        - containerPort: 2222
          protocol: TCP
        env:
        - name: TZ
          value: Africa/Johannesburg
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: /config
          name: openssh-server-volume
      volumes:
      - name: openssh-server-volume
        persistentVolumeClaim:
          claimName: openssh-server-data-pvc
