apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
  labels:
    app: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
      - name: freshrss
        image: linuxserver/freshrss:latest@sha256:075c79de60a0651496e3234ffc3a4d39fe4b8ab76060ea2872febf214c39acda
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/GMT+2"
        volumeMounts:
        - name: freshrss-data
          mountPath: /config
      terminationGracePeriodSeconds: 30
      volumes:
      - name: freshrss-data
        persistentVolumeClaim:
          claimName: freshrss-pvc
