apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
  labels:
    app: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
      - name: freshrss
        image: linuxserver/freshrss:latest@sha256:c6c81f83a14c314b581c458b824476effa38734849d34d9da865d07bc993d287
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/GMT+2"
        volumeMounts:
        - name: freshrss-data
          mountPath: /config
      terminationGracePeriodSeconds: 30
      volumes:
      - name: freshrss-data
        persistentVolumeClaim:
          claimName: freshrss-pvc
